all:
  hosts:
    raspberrypi:
      ansible_host: raspberrypi.local
      ansible_user: pi
      ansible_password: raspberry

    babymonitor:
      ansible_host: babymonitor.local
      ansible_user: pi
      ansible_password: raspberry

    localhost:
      ansible_connection: local
      ansible_user: kallan
      ansible_python_interpreter: "/usr/bin/python3"

    prometheus:
      ansible_host: prometheus.local
      ansible_user: qwertyhowl
