all:
  hosts:
    new-pi:
      raspberrypi:
        ansible_user: pi
        ansible_password: raspberry
        
    babymonitor:
      ansible_user: pi

    localhost:
      ansible_connection: local

vars:
  protected_storage: "~/.protected/ansible"