all:
  hosts:
    raspberrypi:
      ansible_user: pi
      ansible_password: raspberry
        
    babymonitor.local:
      ansible_user: pi
      ansible_password: raspberry

    localhost:
      ansible_connection: local
      repo_codename: bionic
      
