---
- name: Ensure OS is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600

- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - libraspberrypi-dev
      - autoconf
      - automake
      - libtool
      - pkg-config
      - alsa-base
      - alsa-tools
      - alsa-utils
      - fail2ban
      - logwatch
      - mosh
      

- name: Install Node.js
  tasks:
    - name: add apt key for nodesource
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Nodesource Apt Sources Version 6
      apt_repository:
        repo: "{{ repository }}"
        state: present
      vars:
        repository:
          - "deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release|lower }} main"
          - "deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release|lower }} main"

    
    - name: Install NodeJS and NPM
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nodejs
          - nodejs-legacy
          - npm

    - name: Enable RPI Camera
      lineinfile:
        path: /etc/modules
        line: bcm2832_v412
        state: present

- name: Install .local domain resolution
  apt:
    name: avahi-daemon
    state: prsesent

- name: Clone FruitNanny source code
  tasks:
    - name: Making directory for FruitNanny source code
      file:
        path: /opt/fruitnanny
        owner: pi
        group: pi
        state: directory
    
    - name: Cloning FruitNanny source code
      git:
        repo: https://github.com/ivadim/fruitnanny
        dest: /opt/fruitnanny
        clone: yes    

- name: Install Audio and Video Pipeline
  tasks:
    # - name: Install packages
    #   apt:
    #     name: "{{ packages }}"
    #     state: present
    #   vars:
    #     packages:
    #       - gstreamer1.0-tools
    #       - gstreamer1.0-plugins-good
    #       - gstreamer1.0-plugins-bad
    #       - gstreamer1.0-plugins-ugly
    #       - gstreamer1.0-plugins-bad
    #       - libgstreamer1.0-dev
    #       - libgstreamer-plugins-base1.0-dev
    #       - gstreamer1.0-alsa
    - name: Install gstreamer
      apt:
        name: gstreamer1.0
        state: present