---
- name: Ensure OS is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600

- name: Gather package facts
  package_facts:
    manager: apt

- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fail2ban
      - logwatch