---
- name: Ensure OS is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600

- name: Gather package facts
  package_facts:
    manager: apt

- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - libraspberrypi-dev
      - autoconf
      - automake
      - libtool
      - pkg-config
      - alsa-base
      - alsa-tools
      - alsa-utils
      - fail2ban
      - logwatch
      - mosh

- name: Install Node JS
  include: install-nodejs.yml

- name: Enable RPI Camera
  include: rpi-camera.yml

- name: Making directory for FruitNanny source code
  file:
    path: /opt/fruitnanny
    owner: pi
    group: pi
    state: directory

- name: Cloning FruitNanny source code
  git:
    repo: https://github.com/ivadim/fruitnanny
    dest: /opt/fruitnanny
    clone: yes

- name: Install Gstreamer packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-alsa

# raspivid -t 0 -h 720 -w 1080 -fps 25 -hf -b 2000000 -o - | gst-launch-1.0 -v fdsrc ! h264parse !  rtph264pay config-interval=1 pt=96 ! gdppay ! tcpserversink host=YOUR_RPI_IP_ADDRESS port=5000