---
- name: Ensure OS is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - libraspberrypi-dev
      - autoconf
      - automake
      - libtool
      - pkg-config
      - alsa-base
      - alsa-tools
      - alsa-utils