---
- name: add apt key for nodesource
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Nodesource Apt Sources Version 10
  apt_repository:  
    repo: '{{ item }} https://deb.nodesource.com/node_10.x {{ ansible_distribution_release|lower }} main'
    state: present
  with_items:
    - deb
    - deb-src

- name: Install NodeJS
  apt:
    name: nodejs
    state: present
    update_cache: yes
