---
- name: Enable start_x
  lineinfile:
    path: /boot/config.txt
    regex: "^start_x="
    line: "start_x=1"
    state: present
  register: start_x

- name: Enable gpu_mem 128
  lineinfile:
    path: /boot/config.txt
    regex: "^gpu_mem=128"
    line: "gpu_mem=128"
    state: present
  register: gpumem

- name: Rebooting RPI
  reboot:
  when: start_x.changed == True or gpumem.changed == True
