---
- name: Enable start_x
  lineinfile:
    path: /boot/config.txt
    regex: "^start_x="
    line: "start_x=1"
    state: present
  register: start_x

- name: Enable gpu_mem 256
  lineinfile:
    path: /boot/config.txt
    regex: "#?gpu_mem="
    line: "gpu_mem=256"
    state: present
  register: gpumem

- name: Expose camera to /dev/video0
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: "bcm2835-v4l2"
    state: present
  register: video0

- name: Rebooting RPI
  reboot:
  when: start_x.changed or gpumem.changed or video0.changed == True
