---
- name: Add uv4l repository key
  apt_key:
    url: http://www.linux-projects.org/listing/uv4l_repo/lpkey.asc
    state: present

- name: Add uv4l repository
  apt_repository:
    repo: deb http://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main
    state: present
  
- name: Install uv4l packages
  apt:
    name: [
      "uv4l",
      "uv4l-raspicam",
      "uv4l-raspicam-extras",
      "uv4l-server",
      ]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: uv4l

- name: Reboot to enable u4vl
  reboot:
  when: uv4l.changed == True
