---
- name: Gather package facts
  package_facts:
    manager: "auto"

- name: Add rpm key for VSC
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install Visual Studio Code repo
  apt_repository:
    repo: "deb https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: Install Google Chrome
  apt:
    deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  when: "'google-chrome-stable' not in ansible_facts.packages"

- name: Add Etcher repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
    state: present

- name: Add Etcher repository
  apt_repository:
    repo: "deb https://deb.etcher.io stable etcher"
    state: present

- name: Add Insomnia rpm key
  apt_key:
    url: "https://insomnia.rest/keys/debian-public.key.asc"
    state: present

- name: Add Insomnia repository
  apt_repository:
    repo: "deb https://dl.bintray.com/getinsomnia/Insomnia /"
    state: present

- name: Install PPA for Ansible
  apt_repository:
    # codename: "{{ repo_codename }}"
    repo: ppa:ansible/ansible
    state: present

# - name: Ensure os is up to date
#   apt:
#     update_cache: yes
#     # upgrade: full
#     cache_valid_time: 3600

- name: Installing packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ansible
      - aptitude
      - balena-etcher-electron
      - bash-completion
      - code
      - curl
      - darktable
      - git
      - htop
      - insomnia
      - python
      - python-pip
      - python3
      - python3-pip
      - ranger
      - smartmontools
      - snapd
      - software-properties-common
      - tmux
      - tree
      - wget

# Need Ansible 2.8
# - name: Install Snap Packages
#   snap:
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#       - insomnia

- name: Install Pip Packages
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - psutil