---
- name: Gather package facts
  package_facts:
    manager: "auto"

- name: Add rpm key for VSC
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install Visual Studio Code package
  apt:
    name: code
    state: present

- name: Install Google Chrome
  apt:
    deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  when: "'google-chrome-stable' not in ansible_facts.packages"

- name: Add Etcher repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
    state: present

- name: Add Etcher repository
  apt_repository:
    repo: "deb https://deb.etcher.io stable etcher"
    state: present
    update_cache: yes

- name: Install PPA for Ansible
  apt_repository:
    # codename: "{{ repo_codename }}"
    repo: ppa:ansible/ansible
    state: present

- name: Install Pip Packages
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - psutil

- name: Ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 3600

- name: Installing packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ansible
      - balena-etcher-electron
      - bash-completion
      - curl
      - darktable
      - git
      - htop
      - ranger
      - python
      - python3
      - python-pip
      - smartmontools
      - software-properties-common
      - snapd
      - tmux
      - tree
      #   - virtualbox-qt
      #   - virtualbox-ext-pack
      - wget
