# Install UNetbootin
---
- name: Install UNetbootin Repository
  apt_repository:
    codename: "{{ repo_codename }}"
    repo: ppa:gezakovacs/ppa
    state: present
    update_cache: yes

- name: Install UNetbootin
  apt:
    name: unetbootin
    state: present