---
- name: Wait for nodes to become ready for connection
  wait_for_connection:
    # delay: 30 # seconds until begin checking

- name: Wait for automatic updates to finish
  shell: |
    timeout=$(($(date +%s) + 600))

    while pgrep apt > /dev/null; do
      
        time=$(date +%s)

        if [[ $time -ge $timeout ]];
        then
            exit 1
        fi

        sleep 1
    done;
    exit 0

- name: Perform package upgrade
  apt:
    upgrade: dist
  notify: reboot os
