---
# tasks file for new-pi
# Expand filesystem to fill SD Card
- name: Expanding Filesystem
  command: raspi-config --expand-rootfs
    
# Configure localisation
- name: Ensure locale exists
  locale_gen:
    name: "{{ locale }}"
    state: present
- name: Removing default GB locale
  locale_gen:
    name: en_GB.UTF-8
    state: absent

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

# Update and Upgrade apt packages
- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade apt packages
  apt:
    upgrade: dist

# Changes hostname to provided variable
- name: Changing hostname
  hostname:
    name: "{{ hostname }}"